version: '2.4'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: spacetrouble
      POSTGRES_PASSWORD: spacetrouble
      POSTGRES_DB: spacetrouble
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build: docker/postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s